#!/usr/bin/python
# -*- coding: utf-8 -*-

from random import choice

NOUNS = [
    "apple",
    "apricot",
    "artichoke",
    "asparagus",
    "aubergine",
    "banana",
    "bean",
    "beetroot",
    "blackberry",
    "blueberry",
    "broccoli",
    "cabbage",
    "carrot",
    "cashew",
    "cauliflower",
    "celery",
    "cherry",
    "chestnut",
    "chilli pepper",
    "cucumber",
    "date",
    "eggplant",
    "fig",
    "grape",
    "grapefruit",
    "guava",
    "honeydew melon",
    "honeysuckle",
    "jackfruit",
    "kiwifruit",
    "leek",
    "lemon",
    "lime",
    "lettuce",
    "mango",
    "melon",
    "mushroom",
    "nectarine",
    "olive",
    "onion",
    "orange",
    "pea",
    "peach",
    "pear",
    "pepper",
    "pineapple",
    "plum",
    "potato",
    "pumpkin",
    "radish",
    "raspberry",
    "rhubarb",
    "rice",
    "sausage",
    "strawberry",
    "sweet potato",
    "tomato",
    "turnip",
    "watermelon",
]

ADJECTIVES = [
    "active",
    "amusing",
    "beautiful",
    "big",
    "blue",
    "careful",
    "certain",
    "clever",
    "comfortable",
    "cool",
    "dark",
    "easy",
    "elegant",
    "excited",
    "expensive",
    "fair",
    "famous",
    "friendly",
    "funny",
    "good",
    "great",
    "happy",
    "healthy",
    "helpful",
    "hot",
    "important",
    "intelligent",
    "interesting",
    "kind",
    "large",
    "lazy",
    "light",
    "loud",
    "lucky",
    "mean",
    "new",
    "nice",
    "old",
    "original",
    "pretty",
    "quick",
    "quiet",
    "rich",
    "sad",
    "safe",
    "serious",
    "short",
    "smart",
    "small",
    "soft",
    "surprised",
    "sweet",
    "tall",
    "thin",
    "tired",
    "true",
    "ugly",
    "useful",
    "warm",
    "white",
    "wide",
    "young",
]

def generate_name(adjectives, nouns):
    return f"{choice(adjectives)}-{choice(nouns)}"

if __name__ == "__main__":
    print(generate_name(ADJECTIVES, NOUNS))